### ISSUE TITLE
Format von Tags

### ISSUE THREAD

**Issue by mimischi** [ClockGU/clock-backend#37]
Wie sollen die Tags von Schichten denn an die API übergeben werden? Laut Swagger Dokumentation sollen es Strings sein, aber folgender Request funktioniert nicht:

## Request 

```
curl --request POST \
  --url 'http://localhost:8000/api/shifts/' \
  --header 'authorization: Bearer <auth_token>' \
  --header 'content-type: application/json' \
  --data '{
  "started": "2019-06-02T12:30",
  "stopped": "2019-06-02T12:30",
  "contract": "<contract_uuid>",
  "type": "st",
  "tags": "abc"
}'
```

## Error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 78, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 20, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 434, in run_validation
    value = self.to_internal_value(data)
  File "/app/api/serializers.py", line 50, in to_internal_value
    return super(RestrictModificationModelSerializer, self).to_internal_value(data)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 491, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/fields.py", line 536, in run_validation
    value = self.to_internal_value(data)
  File "/app/api/serializers.py", line 19, in to_internal_value
    return json.loads(data)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by chgad** [comment]
Ja, die Tags sollen als ein einzelner string dargestellt werden. Allerdings in einer gewissen Form, wie in dieser Fixture [Fixture ](https://github.com/ClockGU/clock-backend/blob/develop/api/tests/conftest_files/shift_conftest.py#L329) zu sehen ist.

Es sollte also 
    {"tags": '["tag1", "tag2"]'
    }

sein. An der Swagger darstellung muss also noch was gemacht werden.

**Comment by mimischi** [comment]
`{"tags": '["tag1", "tag2"]'}` ist allerdings kein valides JSON.

`{"tags": "[tags1, tags2]"}` und `{"tags": ["tags1", "tags2"]}` funktionieren aber auch nicht.

**Comment by mimischi** [comment]
Ich denke `{"tags": "tag1, tag2"}` ist als Format vollkommen ausreichend. Tags dürfen keine Kommas enthalten.

**Comment by chgad** [comment]
Ne es sollte schon ein JSON array sein, da dieser zur Liste wird und damit kann der `TaggableManager` umgehen.

**Comment by mimischi** [comment]
Dann muss das Format `{"tags": [tag1, tag2]}` ja eigentlich funktionieren?

**Comment by chgad** [comment]
Nein, noch nicht.

**Comment by mimischi** [comment]
Funktioniert jetzt!
